#!/bin/bash
clear
cd Logo && ./introxt_logo
cd ..
echo "Enter the Account Name";
read mail;
echo "Enter Value Accounts starting from gisiniso1..2..3.. From";
read num;
echo "upto";
read value;
j=0;
for ((j=$num;j<=$value;j++))
do
curl -i 'https://www.instagram.com/accounts/web_create_ajax/?hl=en' -H 'origin: https://www.instagram.com' -H 'accept-encoding: gzip, deflate, br' -H 'accept-language: en-US,en;q=0.9' -H 'x-requested-with: XMLHttpRequest' -H 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36' -H 'cookie: csrftoken=inptLrUFmtu8qdM58OR1NLGfGvvC3HN8; rur=FTW; mid=W2H05QAEAAFrY8V-PszhC31RHLxh; mcd=3' -H 'x-csrftoken: inptLrUFmtu8qdM58OR1NLGfGvvC3HN8' -H 'x-instagram-ajax: 0222ed548e52-hot' -H 'content-type: application/x-www-form-urlencoded' -H 'accept: */*' -H 'referer: https://www.instagram.com/accounts/emailsignup/?hl=en' -H 'authority: www.instagram.com' --data 'email='$mail$j'x%40gmail.com&password='$mail'x%40'$j'&username='$mail$j'x&first_name='$mail$j'x&seamless_login_enabled=1&tos_version=row&opt_into_one_tap=false' --compressed -o signup.txt
grep 'csrftoken' signup.txt > csrftoken;
declare -a csrftoken;
csrftoken=($(sed 's/^......................//g' csrftoken));
echo ${csrftoken[0]};
declare -a csrftoken1;
sed -e 's/[;,()'\'']/ /g;s/  */ /g' csrftoken > csrftoken2
csrftoken1=($(sed 's/^......................//g' csrftoken2));
echo ${csrftoken1[0]};
grep 'ds_user_id' signup.txt > ds_user_id
declare -a ds_user_id
ds_user_id=($(sed -e 's/^.......................//g' ds_user_id ));
echo ${ds_user_id[0]};
grep 'session' signup.txt > session
declare -a session
session=($(sed -e 's/^......................//g' session))
echo ${session[0]}
user_id=(1922606959 3567519973 1650532993 5562186409 1731988667 1816804102 2290634214 2197510756 2301912423 )
user_name=(girru_gsb crazyniteshsoni nsnemichand sudarshansinghrathore00 tushar_48 nitishpurohit27 himanshu_gehl0t sunil_khoja vishalsonal)
echo ${user_id[0]};
echo ${user_id[1]};
echo ${user_name[0]};
echo ${user_name[1]};
for ((i=0;i<=2;i++))
do
curl -i 'https://www.instagram.com/web/friendships/'${user_id[$i]}'/follow/' -X POST -H 'origin: https://www.instagram.com' -H 'accept-encoding: gzip, deflate, br' -H 'accept-language: en-US,en;q=0.9' -H 'x-requested-with: XMLHttpRequest' -H 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36' -H 'cookie: csrftoken='${csrftoken[0]}'  ds_user_id='${ds_user_id[0]}' sessionid='${session[0]}' rur=FRC;' -H 'x-csrftoken: '${csrftoken1[0]}'' -H 'x-instagram-ajax: 870097d46f71' -H 'content-type: application/x-www-form-urlencoded' -H 'accept: */*' -H 'referer: https://www.instagram.com/'${user_name[$i]}'/' -H 'authority: www.instagram.com' -H 'content-length: 0' --compressed -o follow.txt
done
done

